name: Autograder in Docker

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub Username'
        required: false  # Set to false if you want this to be optional
        default: ''
      use_external_repo:
        description: 'Use external repository?'
        required: true
        default: 'false'  # Default to local files unless specified

jobs:
  build-and-test: 
    name: Autograding for ${{ github.event.inputs.username }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Git config
      if: inputs.use_external_repo == 'true'
      run: |
        git config --global user.email "davidt@chislgroup.com"
        git config --global user.name "${{ github.actor }}"

    - name: Checkout files from applicant and commit
      if: inputs.use_external_repo == 'true' && inputs.username != ''
      run: |
        git remote add my-assessment https://github.com/${{ github.event.inputs.username }}/my-assessment.git
        git fetch my-assessment
        git checkout my-assessment/main -- Advanced_SQL.py SQL.py
        git add Advanced_SQL.py SQL.py
        git commit -m "Added submission files from ${{ github.event.inputs.username }}"
        git push HEAD:${{ github.ref }}
